### ISSUE TITLE
Do we have to install LaTeX software before we use this tool?

### ISSUE THREAD

**Issue by xiehongle** [uzh-rpg/rpg_trajectory_evaluation#13]
The following errors occurred at runtime：

$ python2 analyze_trajectory_single.py --png ./laptop_vio_mono_MH_01/
Going to analyze the results in ./laptop_vio_mono_MH_01/.
The plots will saved in ./laptop_vio_mono_MH_01/plots.
>>> Calculating errors...
Find evaluation configuration, will overwrite default.
The current evaluation configuration is {'align_type': 'posyaw', 'align_num_frames': -1}
Loading trajectory data...
loading dataset in ./laptop_vio_mono_MH_01/
Loading cached relative (odometry) errors from ./laptop_vio_mono_MH_01/saved_results/cached_rel_err.pickle
Loaded odometry error calcualted at [8.0, 16.0, 32.0, 24.0, 40.0]
...done.
Computing preset subtrajectory lengths for relative errors...
Use percentage [0.1, 0.2, 0.3, 0.4, 0.5] of trajectory length.
...done. Computed preset subtrajecory lengths: [8.0, 16.0, 24.0, 32.0, 40.0]
Aliging the trajectory estimate to the groundtruth...
Alignment type is posyaw.
To align all frames.
... trajectory alignment done.
Calculating RMSE...
Trajectory already aligned
...RMSE calculated.
Computing the relative errors based on preset subtrajectory lengths...
Relative error at sub-trajectory length 8.0 is already computed or loaded from cache.
Relative error at sub-trajectory length 16.0 is already computed or loaded from cache.
Relative error at sub-trajectory length 24.0 is already computed or loaded from cache.
Relative error at sub-trajectory length 32.0 is already computed or loaded from cache.
Relative error at sub-trajectory length 40.0 is already computed or loaded from cache.
>>> Plotting absolute error...
sh: 1: latex: not found
Traceback (most recent call last):
  File "analyze_trajectory_single.py", line 69, in <module>
    fig.tight_layout()
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1754, in tight_layout
    rect=rect)
  File "/usr/lib/python2.7/dist-packages/matplotlib/tight_layout.py", line 349, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/usr/lib/python2.7/dist-packages/matplotlib/tight_layout.py", line 126, in auto_adjust_subplotpars
    tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots])
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 3679, in get_tightbbox
    bb_xaxis = self.xaxis.get_tightbbox(renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 1075, in get_tightbbox
    renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 1058, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/text.py", line 961, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/text.py", line 352, in _get_layout
    ismath=False)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 229, in get_text_width_height_descent
    renderer=self)
  File "/usr/lib/python2.7/dist-packages/matplotlib/texmanager.py", line 675, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/usr/lib/python2.7/dist-packages/matplotlib/texmanager.py", line 422, in make_dvi
    report))
RuntimeError: LaTeX was not able to process the following string:
'lp'
Here is the full report generated by LaTeX:

**Comment by zhangzichao** [comment]
Yes, by default we need that for plotting, or you can switch it off as described in this issue #1

**Comment by aserbremen** [comment]
I had latex install but got this similar error as above but saying at the end:
`OSError: [Errno 2] No such file or directory: 'dvipng'`

I installed dvipng package
`sudo apt install dvipng`
and it worked afterwards
